# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Hl7tools < Formula
  desc "Tools to assist with developing and testing HL7 interfaces."
  homepage ""
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chzmnky/HL7Tools/releases/download/v0.1.1/HL7Tools_0.1.1_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "9fb84b651dcef2e7e11e3df77042811194ad0617dff39b6dcd735beeb7b805df"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chzmnky/HL7Tools/releases/download/v0.1.1/HL7Tools_0.1.1_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "126567a3eaafd42d97ee83bffd1f9e15d09936f1b3737e2296a2503843fa6340"
    end
  end

  def install
    bin.install "hl7player"
  end
end
