# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Hl7tools < Formula
  desc "Tools to assist with developing and testing HL7 interfaces."
  homepage ""
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chzmnky/HL7Tools/releases/download/v0.1.1/HL7Tools_0.1.1_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "b7305034c73f702e3d0ce79fb72e6e2594d30056ee3258f6a0f9ea4c1faeaa32"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chzmnky/HL7Tools/releases/download/v0.1.1/HL7Tools_0.1.1_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7856925784595c269d4143baa64cea216292d4e7959603af8b3fd104a924c5eb"
    end
  end

  def install
    bin.install "hl7player"
  end
end
